<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Shipment Report PDF</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #000; padding: 5px; text-align: left; }
        th { background: #eee; }
        h2 { text-align: center; margin-bottom: 10px; }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <div class="brand">
            <h1>{{ config('app.name', 'StepUp Courier') }}</h1>
        </div>
        <div class="meta">
            <div><strong>Date:</strong> {{ now()->format('d M, Y') }}</div>
            <div><strong>Generated By:</strong> {{ Auth::user()->name ?? 'System' }}</div>
        </div>
    </div>

    <h2>Shipment Report</h2>
    <p class="subtitle">
        Status: <strong>{{ ucfirst(str_replace('_',' ',$status)) }}</strong>
    </p>

    <table>
        <thead>
            <tr>
                <th>Tracking</th>
                <th>Delivery Man</th>
                <th>Status</th>
                <th>Amount (BDT)</th>
                <th>Merchant</th>
                <th>Customer</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
        @foreach($shipments as $shipment)
            <tr>
                <td>{{ $shipment->tracking_number }}</td>
                <td>{{ $shipment->courier->user->name ?? '—' }}</td>
                <td>{{ ucfirst(str_replace('_',' ',$shipment->status)) }}</td>
                <td>{{ number_format($shipment->price, 2) }}</td>
                <td>{{ $shipment->customer->business_name }} - {{ $shipment->customer->phone}} <br> {{ $shipment->customer->business_address }}</td>
                <td>{{ $shipment->drop_name }} - {{ $shipment->drop_phone }} <br> {{ $shipment->drop_address }}</td>
                <td>{{ $shipment->notes }}</td>
            </tr>
        @endforeach
        </tbody>
    </table><br>

     <footer>
        Generated by {{ config('app.name', 'StepUp Courier') }} | {{ now()->format('d M Y, h:i A') }}
    </footer>

</body>
</html>
