<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Delivery Man Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        h2, h3 { margin: 0; padding: 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #000; padding: 5px; text-align: left; }
        th { background: #eee; }
        .header { display: flex; justify-content: space-between; align-items: center; }
        .header div { line-height: 1.2; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h2>{{ config('app.name', 'Courier System') }}</h2><br>
            <h3>{{ $courier->user->name }} — Delivery Man</h3>
        </div>
        <div>
            <div><strong>Date:</strong> {{ now()->format('d M, Y') }}</div>
            <div><strong>Generated By:</strong> {{ Auth::user()->name ?? 'System' }}</div>
        </div>
        <div>
            <strong>Total Parcel:</strong> {{ $totalParcel }}<br>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Tracking</th>
                <th>Status</th>
                <th>Amount (BDT)</th>
                <th>Merchant</th>
                <th>Customer</th>
                <th>Pickup</th>
                <th>Dropoff</th>
                <th>Notes</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($shipments as $shipment)
            <tr>
                <td>{{ $shipment->tracking_number }}</td>
                <td>{{ ucfirst(str_replace('_',' ',$shipment->status)) }}</td>
                <td>{{ number_format($shipment->price, 2) }}</td>
                <td>{{ $shipment->customer->business_name ?? '—' }} <br> {{ $shipment->customer->phone ?? '' }}</td>
                <td>{{ $shipment->drop_name ?? '—' }} <br> {{ $shipment->drop_phone ?? '' }}</td>
                <td>{{ $shipment->user->business_address }}</td>
                <td>{{ $shipment->drop_address }}</td>
                <td>{{ $shipment->notes ?? '-' }}</td>
                <td>{{ $shipment->created_at->format('d M, Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>
